SELECT JN_DATE
,      GN_DATE
,      TO_CHAR(GN_DATE,'Day') DAY_NAME 
,      TO_NUMBER(TO_CHAR(GN_DATE,'DD')) DAY_NUMBER
,      TO_NUMBER(TO_CHAR(GN_DATE,'MM')) MONTH_NUMBER
,      TO_NUMBER(TO_CHAR(GN_DATE,'YYYY')) YEAR
,      TO_NUMBER(TO_CHAR(GN_DATE,'YYYY')||TO_CHAR(GN_DATE,'MM')) MONTH_YEAR_NUM
,      TO_CHAR(GN_DATE,'MON') MONTH_NAME3
,      TO_CHAR(GN_DATE,'Month') MONTH_NAME
,      NEXT_DAY(GN_DATE,'SUNDAY')-7 WEEK_START_DATE
,      TRUNC((JN_DATE-TO_NUMBER(TO_CHAR(NEXT_DAY(TO_DATE('01-JAN-'||TO_CHAR(GN_DATE,'YYYY')),'MONDAY')-7 ,'J'))) /7)+1  WEEK_OF_YEAR
--,      TO_NUMBER(TO_CHAR(GN_DATE, 'WW')) WEEK_NUM
,      TRUNC((JN_DATE-TO_NUMBER(TO_CHAR(NEXT_DAY(TO_DATE('01-'||TO_CHAR(GN_DATE,'MON')||'-'||TO_CHAR(GN_DATE,'YYYY')),'MONDAY')-7 ,'J'))) /7)+1  WEEK_OF_MONTH
,      (CASE  TO_CHAR(GN_DATE,'MM') 
        WHEN  '01' THEN 'Q1'
        WHEN  '02' THEN 'Q1'
        WHEN  '03' THEN 'Q1'
        WHEN  '04' THEN 'Q2'
        WHEN  '05' THEN 'Q2'
        WHEN  '06' THEN 'Q2'
        WHEN  '07' THEN 'Q3'
        WHEN  '08' THEN 'Q3'
        WHEN  '09' THEN 'Q3'
        WHEN  '10' THEN 'Q4'
        WHEN  '11' THEN 'Q4'
        WHEN  '12' THEN 'Q4'
        ELSE  '00'
       END)  QUARTER_NUMBER
,      (GN_DATE -1)  DAY_AGO_DATE
,      ADD_MONTHS(GN_DATE, -1) MONTH_AGO_DATE
,      (GN_DATE -7)  WEEK_AGO_DATE       
,      ADD_MONTHS(GN_DATE,  -12)     YEAR_AGO_DATE 
,      TO_NUMBER(TO_CHAR(GN_DATE,'YYYY'))-2014 YEAR_SEQ
,      (TO_NUMBER(TO_CHAR(GN_DATE,'YYYY'))-2014)*12+TO_NUMBER(TO_CHAR(GN_DATE,'MM')) MONTH_SEQ
,      TRUNC((JN_DATE-TO_NUMBER(TO_CHAR(NEXT_DAY(TO_DATE('01-JAN-2014'),'SUNDAY')-7 ,'J'))) /7)  WEEK_SEQ
--,NEXT_DAY(TO_DATE('01-JAN-2014'),'SUNDAY')-7
--,TO_CHAR(NEXT_DAY(TO_DATE('01-JAN-2014'),'SUNDAY')-7 ,'J')
--,TO_NUMBER(TO_CHAR(NEXT_DAY(TO_DATE('01-JAN-2014'),'SUNDAY')-7 ,'J'))
--,JN_DATE-TO_NUMBER(TO_CHAR(NEXT_DAY(TO_DATE('01-JAN-2014'),'SUNDAY')-7 ,'J'))
FROM TABLE(get_day_rows(2014,2015))
/