select TRUNC(TO_NUMBER((TO_CHAR(SYSDATE,'J'))-TO_NUMBER(TO_CHAR(NEXT_DAY(TO_DATE('01-JAN-2014'),'SUNDAY')-7 ,'J'))) /7) CURRENT_WEEK_SEQ
,      (TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))-2014)*12+TO_NUMBER(TO_CHAR(SYSDATE,'MM')) CURRENT_MONTH_SEQ
,      TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))-2014 CURRENT_YEAR_SEQ
from dual;